/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as TidesRouteImport } from './routes/tides'
import { Route as SosRouteImport } from './routes/sos'
import { Route as MarketRouteImport } from './routes/market'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const TidesRoute = TidesRouteImport.update({
  id: '/tides',
  path: '/tides',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chat': typeof ChatRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/sos': typeof SosRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chat': typeof ChatRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/sos': typeof SosRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chat': typeof ChatRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/sos': typeof SosRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/chat'
    | '/features'
    | '/market'
    | '/sos'
    | '/tides'
    | '/vessels'
    | '/voice'
    | '/weather'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/chat'
    | '/features'
    | '/market'
    | '/sos'
    | '/tides'
    | '/vessels'
    | '/voice'
    | '/weather'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/chat'
    | '/features'
    | '/market'
    | '/sos'
    | '/tides'
    | '/vessels'
    | '/voice'
    | '/weather'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ChatRoute: typeof ChatRoute
  FeaturesRoute: typeof FeaturesRoute
  MarketRoute: typeof MarketRoute
  SosRoute: typeof SosRoute
  TidesRoute: typeof TidesRoute
  VesselsRoute: typeof VesselsRoute
  VoiceRoute: typeof VoiceRoute
  WeatherRoute: typeof WeatherRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tides': {
      id: '/tides'
      path: '/tides'
      fullPath: '/tides'
      preLoaderRoute: typeof TidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ChatRoute: ChatRoute,
  FeaturesRoute: FeaturesRoute,
  MarketRoute: MarketRoute,
  SosRoute: SosRoute,
  TidesRoute: TidesRoute,
  VesselsRoute: VesselsRoute,
  VoiceRoute: VoiceRoute,
  WeatherRoute: WeatherRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
